
experiments:
  - name: "experiment_1"
    description: "No windowing - seq-to-seq"
    data:
      data_dir: "/data/bnd-data/raw/"
      session: "M062_2025_03_21_14_00"
      epoch: [-1, 3]
      combine_time_bins: true
      sigma: 1
    model:
      hidden_size: 300
      num_layers: 2
      input_dim: 20
      outputs: ["right_knee", "left_knee", "hip_center"]
      dropout: 0
    training:
      learning_rate: 0.001
      batch_size: 1024
      epochs: 1
      condition: 'trial'
      areas: ['MOp']
      window_data: false
      len_window: 5
      k: 2
      n_print_epoch: 250
    results:
      r2_window: 10
      results_dir: "/home/me24/repos/earthquake-analysis/results/lstm/experiment_1/"
      plot_example: true
    logging:
      log_dir: "/home/me24/repos/earthquake-analysis/results/lstm/experiment_1/experiment_1.log"

  - name: "experiment_2"
    description: "Windowing - seq-to-point"
    data:
      data_dir: "/data/bnd-data/raw/"
      session: "M062_2025_03_21_14_00"
      epoch: [-1, 3]
      combine_time_bins: true
      sigma: 1
    model:
      hidden_size: 300
      num_layers: 2
      input_dim: 20
      outputs: ["right_knee", "left_knee", "hip_center"]
      dropout: 0
    training:
      learning_rate: 0.001
      batch_size: 3000
      epochs: 1
      condition: 'trial'
      areas: ['MOp']
      window_data: true
      len_window: 5
      k: 2
      n_print_epoch: 250
    results:
      r2_window: 10
      results_dir: "/home/me24/repos/earthquake-analysis/results/lstm/experiment_2/"
      plot_example: true
    logging:
      log_dir: "/home/me24/repos/earthquake-analysis/results/lstm/experiment_2/experiment_2.log"

